### ISSUE TITLE
Array at feed level will only show first item

### ISSUE THREAD

**Issue by advdberg** [rbren/rss-parser#94] opened 2019-02-04 07:18 UTC
I'm dealing with a feed with multiple custom nodes at feed level. I can configure it as a custom field at feed level, but then only the first node will be parsed. 

If I configure this node as a custom field array at feed level (just like it can be done on item level) I cannot compile:

const customFields: CustomFields = {
      feed: [
        ["stand:ranking","stand:ranking", {keepArray: true}],
      ]
    }

![image](https://user-images.githubusercontent.com/28447261/52194664-0a33aa00-2855-11e9-88bc-c77d4a7c3612.png)

**Comment by bobby-brennan** [comment] 2019-02-06 17:47
Hi there,

It looks like we need to change [the typings file](https://github.com/bobby-brennan/rss-parser/blob/master/index.d.ts#L9) so that you can pass in the `keepArray` option. I'm not an expert on TS, but would happily accept a PR to that effect.

**Comment by maxsteenbergen** [comment] 2019-12-18 17:42
I'm dealing with this exact same issue on this exact same RSS feed (hallo @advdberg! 👋 ) 
Any thoughts on how I might proceed? I'm not an expert on TS as well and wouldn't know what to change.

**Comment by advdberg** [comment] 2019-12-19 08:20
Hi @maxsteenbergen, I've used the description in this case and extracted the values from the full string. For my purpose this was enough. I'm not a TS expert as well so updating the package will take me too much time.

**Comment by campriceaustin** [comment] 2020-01-27 00:56
I'm getting this on the items in a standard RSS feed too e.g. parsing http://rss.art19.com/the-daily, the `items` collection only contains the oldest (last) `item` in the feed.

**Comment by rbren** [comment] 2020-01-28 20:32
I think this is fixed in https://github.com/rbren/rss-parser/pull/148 - if not feel free to reopen

**Comment by rbren** [comment] 2020-01-28 20:38
(that's version `3.7.4`)

**Closed by rbren** 2020-01-28 20:38 UTC

**Comment by maxsteenbergen** [comment] 2020-01-29 12:41
I can confirm this works with a vanilla JS implementation -> https://jsfiddle.net/zxdgyowf/2/ 
I haven't had such luck yet with getting it to work with Gatsby/Graphql via https://github.com/mottox2/gatsby-source-rss-feed but at least the core functionality works. Thanks 👍
